name:
  .trash: ï‡¸
  .cargo: î¨
  .emacs.d: î¹
  a.out: ï’‰
extension:
  go: î˜§
  hs: î·
  rs: ğŸ¦€
  7z: ï‡†
  ai: î´
  bat: î˜•
  bmp: î˜
  bz: ï‡†
  bz2: ï‡†
  c: î˜
  "c++": î˜
  cc: î˜
  clj: î¨
  cljc: î¨
  cljs: îª
  coffee: î˜›
  conf: î˜•
  cp: î˜
  cpp: î˜
  css: î˜”
  cxx: î˜
  d: î¯
  dart: î˜
  db: îœ†
  diff: îœ¨
  dump: îœ†
  edn: îª
  ejs: î˜
  erl: î±
  "f#": î§
  fish: î•
  fs: î§
  fsi: î§
  fsscript: î§
  fsx: î§
  gif: î˜
  gz: ï‡†
  hbs: î˜
  hrl: î±
  htm: î˜
  html: î˜
  ico: î˜
  ini: î˜•
  java: îœ¸
  jl: î˜¤
  jpeg: î˜
  jpg: î˜
  js: î˜Œ
  json: î˜‹
  jsx: îº
  less: î˜”
  lhs: î˜Ÿ
  lua: î˜ 
  markdown: î˜‰
  md: î˜‰
  ml: Î»
  mli: Î»
  mustache: î˜
  php: î˜ˆ
  pl: î©
  pm: î©
  png: î˜
  psb: î¸
  psd: î¸
  py: î˜†
  pyc: î˜†
  pyd: î˜†
  pyo: î˜†
  rb: î‘
  rlib: î¨
  rss: î˜™
  scala: îœ·
  scss: î˜ƒ
  sh: î•
  slim: î˜
  sln: îœŒ
  sql: îœ†
  styl: î˜€
  suo: îœŒ
  t: î©
  tar: ï‡†
  ts: î˜¨
  twig: î˜œ
  txt: ïƒ¶
  vim: îŸ…
  xul: î…
  xz: ï‡†
  yml: î˜•
  zip: ï‡†
filetype:
  dir: ï„•
  file: ï€–
  pipe: ï’
  socket: îœ¨
  executable: ï’‰
  symlink-dir: ï’‚
  symlink-file: ï’
  device-char: î˜
  device-block: îœ·
  special: ï‹œ
